image: golang:1.11-alpine

stages:
    - test

before_script:
  - mkdir -p /go/src/ehw2018.io/greetings-server/
  - cp -fr ../greetings-server /go/src/ehw2018.io
  - cd /go/src/ehw2018.io/greetings-server

exec_test:
    stage: test
    tags:
        - test
    script:
        - apk add make
        - apk add git
        - go get -u github.com/golang/dep/cmd/dep
        - make depensure
        - make bin/greetings-server
        - make test
