image: golang:1.11-alpine

stages:
    - test

exec_test:
    stage: test
    tags:
        - test
    script:
        - apk add make
        - apk add git
        - go get -u github.com/golang/dep/cmd/dep
        - make depinit
        - make bin/greetings-server
        - make test
